NAME            = opt-PyYAML
VERSION         = 3.11
RELEASE 	= 0

SOURCE_DIR	= PyYAML-$(VERSION)

SRC_SUBDIR         = PyYAML

SOURCE_NAME        = PyYAML
SOURCE_VERSION     = $(VERSION)
SOURCE_SUFFIX      = tar.gz
SOURCE_PKG         = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR         = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

TAR_GZ_PKGS           = $(SOURCE_PKG)

