help:
	@echo "make install - install the python libraries"
	@echo "make run     - run the rest server"
	@echo "make view    - view the documentation fior the server"
	@echo "make edit    - edit the server run.py, use your own edit method"
	@echo "make manual  - look up swagger doccumentation add ons"

install:
	pip install -r requirements.txt

run:
	python run.py

view:
	open http://localhost:5000

edit:
	e run.py

manual:
	open http://flask-restplus.readthedocs.org/en/latest/
