#!/bin/bash

CELERYD_NODES="nucleus_service_worker"

# Absolute or relative path to the 'celery' command:
CELERY_BIN="/opt/python/bin/celery"

# App instance to use
# comment out this line if you don't use an app
CELERY_APP="nucleus"

# Where to chdir at start.
CELERYD_CHDIR="/opt/python/lib/python2.7/site-packages/nucleus_service"

# Extra command-line arguments to the worker
CELERYD_OPTS="--concurrency=4"

# %N will be replaced with the first part of the nodename.
CELERYD_LOG_FILE="/var/log/celery/%N.log"
CELERYD_PID_FILE="/var/run/celery/%N.pid"

# Workers should run as an unprivileged user.
#   You need to create this user manually (or you can choose
#   a user/group combination that already exists, e.g. nobody).
CELERYD_USER="root"
CELERYD_GROUP="root"

# If enabled pid and log directories will be created if missing,
# and owned by the userid/group configured.
CELERY_CREATE_DIRS=1
