# Virtual Cluster REST API 
swagger: '2.0'
info:
  title: Virtual Cluster REST API
  description:  Comet REST API Specification. 
  version: "1.0.1"
# the domain of the service
host: comet.sdsc.edu
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /clusters:
    get:
      summary: The list of the clusters
      description: |
        The list of the clusters.
      parameters:
        - name: username
          in: query
          description: The user to which the clustes belong.
          required: false
          type: string
        - name: project
          in: query
          description: The project to which the clustes belong.
          required: false
          type: string
        - name: starttime
          in: query
          description: The start time of from which to search.
          required: false
          type: string
        - name: endtime
          in: query
          description: The end time from which to search.
          required: false
          type: string
      tags:
        - Cluster
      responses:
        200:
          description: An array of clusters
          schema:
            type: array
            items:
              $ref: '#/definitions/Cluster'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /cluster:
    tags:
    - Cluster
    get:
      summary: return information about a cluster
      description: return information about a cluster
      responses:
        200:
          description: An array of projects
          schema:
            type: array
            items:
              $ref: '#/definitions/ComputeMaster'
          schema:
            type: array
            items:
              $ref: '#/definitions/ComputeServer'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /projects:
    tags:
    - Project
    get:
      summary: The list of all projects that are allowed to create clusters
      description: |
        The list of projects that are allowed to create clusters. 
      responses:
        200:
          description: An array of projects
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /user:
    get:
      summary: User Profile
      description: The User profile contains information about the user that manages the cluster.
      tags:
        - User
      parameters:
        - name: username
          in: query
          description: Return the profile of the user.
          required: true
          type: string
      responses:
        200:
          description: Profile information for a user
          schema:
            $ref: '#/definitions/Profile'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Cluster:
    tags:
    - Cluster
    type: object
    properties:
      id:
        type: string
        description: a unique id for the cluster
  Clusters:
    tags:
    - Cluster
    type: array
      items:
        $ref: '#/definitions/Cluster'  
  ComputeMaster:
    tags:
    - Compute
    type: object
    properties:
      name:
        type: string
        description: the compute resource name.
  ComputeServer:
    tags:
    - Compute
    type: object
    properties:
      name:
        type: string
        description: the compute resource name.
  StoragePool:
    tags:
    - Storage
    type: object
    properties:
      name:
        type: string
        description: the storage pool name.
  StorageVolume:
    tags:
    - Storage
    type: object
    properties:
      name:
        type: string
        description: the storage volume name.
  StorageServer:
    tags:
    - Storage
    type: object
    properties:
      name:
        type: string
        description: the storage server name.
  StorageTarget:
    tags:
    - Storage
    type: object
    properties:
      name:
        type: string
        description: the storage target name.
  Project:
    tags:
    - Project
    type: object
    properties:
      name:
        type: string
        description: the project name.
  Profile:
    tags:
    - User
    type: object
    properties:
      username:
        type: string
        description: username of the user.
      firstname:
        type: string
        description: First name of the user.
      lastname:
        type: string
        description: Last name of the user.
      email:
        type: string
        description: Email address of the user.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
