NAME            = MySQL-python
VERSION         = 1.2.5
RELEASE 	= 0

SOURCE_DIR	= $(NAME)-$(VERSION)

SRC_SUBDIR         = $(NAME)

SOURCE_NAME        = $(NAME)
SOURCE_VERSION     = $(VERSION)
SOURCE_SUFFIX      = zip
SOURCE_PKG         = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR         = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

ZIP_PKGS           = $(SOURCE_PKG)

